### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by xuyu666** [Ldhlwh/DFMGAN#10]
您好，
我原本使用torch 1.7.1+cu110的环境能跑您的训练和测试，然后今天突然不行了。upfirdn2d这步卡死，撤销后报错
报错信息：Failed to build CUDA kernels for upfirdn2d. UserWarning: Failed to build CUDA kernels for upfirdn2d. 
![image](https://github.com/Ldhlwh/DFMGAN/assets/49869475/8e57e3c4-306b-431c-a584-e41befbeaa94)
![image](https://github.com/Ldhlwh/DFMGAN/assets/49869475/bf6cf41b-b4e2-459e-b563-baa21ab1ecc7)
随后去stylegan-ada Issue里面找，跟着下方图一的回答走更换成了 1.8.0+cu111，还是不行，试了不少方法没成功，您能给点建议么~
![image](https://github.com/Ldhlwh/DFMGAN/assets/49869475/69d892cb-6b28-49a6-be77-b9213147b747)

![image](https://github.com/Ldhlwh/DFMGAN/assets/49869475/5c955805-2079-4524-a259-f4801565931f)

**Comment by Ldhlwh** [comment]
可以尝试清cache
https://github.com/NVlabs/stylegan2-ada-pytorch/issues/215#issuecomment-1108537473

**Comment by xuyu666** [comment]
谢谢哥，解决了~

**Comment by lzxssz** [comment]
> 谢谢哥，解决了~

您好，请问您是怎么解决的，困扰了我好几天了

**Comment by Bubble-water** [comment]
windows系统环境
1、# 清理PyTorch扩展缓存，清理掉之前生成旧的torch cuda的插件
rmdir /s /q "%LOCALAPPDATA%\torch_extensions"
2、直接下载安装指定的Visual Studio版本，然后以管理员权限打开x64 Native Tools Command Prompt终端
2.1如果你安装的是高版本Visual Studio
VS2022 环境中使用 VS2019 工具集(VS2022安装时包含了VS2019的工具集，勾选了MSVC v142)
以管理员权限打开x64 Native Tools Command Prompt for VS2022,然后运行下面使用vs2019
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.29
2.2如果cuda版本很低可以使用vs2017版本
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.16
3、在终端使用python环境
在终端激活你的虚拟环境或者运行你的python环境就能正确编译其upfirdn2d_plugin cuda代码了
