### ISSUE TITLE
Unable to train the defect mask

### ISSUE THREAD

**Issue by wdz0214** [Ldhlwh/DFMGAN#12]
I trained self-built dataset with your code. However, during the defect transfer phase, I found that it is unable to generate defects and the corresponding masks when using the original settings. I tried to adjust the values of lambda-ms and lambda-match many times, defects finally generated when I reduce the value of lambda-match to 0.2 even more smaller. That is to say, mask matching operation hinders defect generation in my dataset. I am so confused, can you give me some suggestions? The following is the failure case of the mask generation. 
![image](https://github.com/Ldhlwh/DFMGAN/assets/110075684/beff1e08-eb60-45e2-b7bf-7fea3135e0f6)
![image](https://github.com/Ldhlwh/DFMGAN/assets/110075684/cb32a68e-8181-4a6b-8db9-876e3d084ed6)

**Comment by Ldhlwh** [comment]
Hello @dezhou02014,

Could you show some examples of your dataset images, including normal images, defect images and masks?

**Comment by dezhou02014** [comment]
> Hello @dezhou02014,
> 
> Could you show some examples of your dataset images, including normal images, defect images and masks?
Thank you very much. I sent them to you through the email provided in your paper.

**Comment by Ldhlwh** [comment]
I saw the examples you sent me. I'm confused since they seem different to the figures you showed in the post above.

Generally trying different hyperparameter settings is needed for the best performance on a specific dataset

**Comment by dezhou02014** [comment]
> 

Thank you. After numerous attempts, I finally discovered the fundamental problem. The mask label must be converted to MVTec format (uint8 format), whereas I previously converted it directly to a binary mask image (not uint8 format) through labelme.
