### ISSUE TITLE
单张图片多种类型缺陷的生成

### ISSUE THREAD

**Issue by ZHIZIHUABU** [Ldhlwh/DFMGAN#14]
感谢您的工作！模型针对单个类型缺陷生成的效果不错，但是在我的数据集中，一张图片存在多种类型的缺陷，那么如果我需要生成包含多种缺陷的单个图像，那么我需要分别为每一类缺陷创建数据集，然后同时训练多个模型，每个模型生成一类缺陷然后再图片上叠加吗？这样操作过于复杂，而且生成的缺陷在下一步缺陷生成时会互相干扰吗？
我的GPU内存只有6G，我可以调整哪些参数减小模型的尺寸呢？

**Comment by Ldhlwh** [comment]
您好 @ZHIZIHUABU，

关于同一张图生成多类缺陷，或许有multi-label的方法可以结合DFMGAN试一下，但我不太了解这方面

关于显存限制问题，可以参考 #7

**Comment by ZHIZIHUABU** [comment]
好的，谢谢，您了解类似的比较先进的图像缺陷生成的工作吗？在工业界缺陷样本生成很重要，但是很难找到开源并且生成效果真实的模型。

**Comment by ZHIZIHUABU** [comment]
我使用训练的模型进行推理，发现推理结果完全不对，但是generate.py并没有需要训练的参数，这是什么原因引起的呢？
![0_img](https://github.com/Ldhlwh/DFMGAN/assets/80161587/ea0aa5a1-1c83-417d-8d57-917c123d602b)
![1_img](https://github.com/Ldhlwh/DFMGAN/assets/80161587/ecb4af49-290f-41ad-a5ad-8daea9d7233c)
![Uploading fakes000400_img.png…]()
![Uploading reals.png…]()
训练过程中log日志生成的图是正常的

**Comment by ZHIZIHUABU** [comment]
![fakes000400_img](https://github.com/Ldhlwh/DFMGAN/assets/80161587/9250c635-ded7-44c5-93a9-e18ddbcea304)
![reals](https://github.com/Ldhlwh/DFMGAN/assets/80161587/f6a1f672-e5cd-4da2-a410-322da1b37ed3)

**Comment by Ldhlwh** [comment]
从上传的图片无法判断问题在哪，请确认没有修改代码且参数设置正确了

**Comment by bookkkker** [comment]
你好，请问你做的是PCB缺陷生成吗，可以交流一下吗
