### ISSUE TITLE
bias_act和upfirdn2d插件问题

### ISSUE THREAD

**Issue by wwt123-star** [Ldhlwh/DFMGAN#15]
训练时一直显示ImportError: No module named bias_act_plugin和upfirdn2d_plugin的警告，发现在使用torch.utils.cpp_extension.load的时候没有生成bias_act.o、bias_act.cuda.o、bias_act_plugin.pyd这些文件，请问这该怎么解决？

**Comment by Ldhlwh** [comment]
您好 @wwt123-star，

这个问题通常是因为环境没有配好，请参照https://github.com/NVlabs/stylegan2-ada-pytorch#requirements配置

**Comment by wwt123-star** [comment]
请问是可以直接在windows的pycharm上运行train.py吗

**Comment by Ldhlwh** [comment]
我没有在windows环境测试过，如果能把stylegan的环境配置好的话可能还需要修改部分代码

**Comment by wwt123-star** [comment]
> 我没有在windows环境测试过，如果能把stylegan的环境配置好的话可能还需要修改部分代码

那应该怎么改才好呢，可否提供点建议

**Comment by Ldhlwh** [comment]
根据报错改就好了，我预计可能会有个别文件系统相关的操作需要改，主要要解决的还是环境问题

**Comment by wwt123-star** [comment]
> 根据报错改就好了，我预计可能会有个别文件系统相关的操作需要改，主要要解决的还是环境问题

倒是没有其他报错，主要还是一直跳ImportError: No module named bias_act_plugin和upfirdn2d_plugin的警告

**Comment by Ldhlwh** [comment]
这个还是环境没配好的问题，可以到stylegan2-ada的库的issue里找解决方案

**Comment by wwt123-star** [comment]
> 这个还是环境没配好的问题，可以到stylegan2-ada的库的issue里找解决方案

好的谢谢
