### ISSUE TITLE
产生的一些artifacts

### ISSUE THREAD

**Issue by leixiaoning** [Ldhlwh/DFMGAN#16]
![image](https://github.com/Ldhlwh/DFMGAN/assets/30723885/67b9c9ca-29f7-43d8-8b60-6a21dbc68c4c)
请问，紫色的这部分缺陷 是什么造成的，有遇到过吗

**Comment by Ldhlwh** [comment]
类似的现象遇到过，训练过程中如果mask比实际缺陷范围大，在填充mask内非实际缺陷部分的时候就可能会产生artifact

**Comment by Jeff0121** [comment]
@Ldhlwh 您好，幾個有關mask的問題請教您:
1. 使用custom dataset時，有時候會產生類似氣泡的artifacts，像您paper p. 27這樣的圖例 ( defect位置不精確會跑到背景中且顏色開始發生變化，是否因為mask範圍過小，而discriminator層數多，卷積太多次後，feature map訊息丟失過多所導致的位置不精確
![image](https://github.com/Ldhlwh/DFMGAN/assets/50964062/36ca1bbb-f245-445c-93c5-6c14606cdea8)
2. augment的value在原始styleganv2ada中，建議要小於0.8以內，但我總是train 1200kimgs後 我的資料集才會有比較好的效果，這時augment已經是1.X了，這樣是否正常呢?

**Comment by Ldhlwh** [comment]
@Jeff0121 
1. 如果缺陷比较细小或者缺陷不是很明显的时候比较容易出现这种情况
2. StyleGAN2ADA所用的数据集基本上至少有一百张图，如果图片更少的话过拟合情况更严重，所以p会更大。如果觉得augmentation太强影响了图像质量可以尝试不加augmentation
