### ISSUE TITLE
关于KID指标的问题

### ISSUE THREAD

**Issue by aaahuaaa** [Ldhlwh/DFMGAN#17]
你好，在生成的图片质量不差的情况下，为何我得到的kid指标为0.03几，想知道关于代码中计算kid的值是有什么讲究吗？
--我的超参数均设置为默认，图片为256*256，pretrain的kimg=3000，transfer的kimg=300

**Comment by Ldhlwh** [comment]
论文中报的KID为乘10^3以后的结果，例如0.030会被报为30
