### ISSUE TITLE
About Stage2 resume the pretraining

### ISSUE THREAD

**Issue by Y-JIE-CREATER** [Ldhlwh/DFMGAN#19]
您好，LdhIwh!!!首先感谢您将代码开源，我认为这对缺陷生成领域有着巨大贡献。同时，我有下面的一个问题，还望您指教。
在第一阶段训练好后，我尝试训练第二阶段。但是当训练到kimg=80.0时，程序意外停止(报错信息如下)。
```python
numpy.core._exceptions.MemoryError: Unable to allocate 64.0 MiB for an array with shape (2048, 2048) and data type complex128
```
为了节约时间，当我再次尝试运行时，我更改了加载的预训练模型为network-snapshot-000080.pkl，执行命令为：
```python
python train.py --data ./data/hazelnut_hole_mask.zip -outdir runs/hazelnut_hole \
--resume runs/hazelnut_hole/00000-hazelnut_hole_mask-auto1-kimg400-resumecustom/network-snapshot-000080.pkl \
--gpus 1 --kimg 400 --snap 10 --transfer res_block_match_dis
```
我想知道这是否会影响我的训练结果

**Comment by Ldhlwh** [comment]
应该不会有太大的影响，但由于中断后再继续训练会重置某些参数（例如ada的超参、优化器等），训练过程有可能会和不中断不太一样，可以参考stylegan部分的代码

**Comment by Y-JIE-CREATER** [comment]
> 应该不会有太大的影响，但由于中断后再继续训练会重置某些参数（例如ada的超参、优化器等），训练过程有可能会和不中断不太一样，可以参考stylegan部分的代码

好的，感谢！

**Comment by Y-JIE-CREATER** [comment]
> 应该不会有太大的影响，但由于中断后再继续训练会重置某些参数（例如ada的超参、优化器等），训练过程有可能会和不中断不太一样，可以参考stylegan部分的代码

好的，感谢！
