### ISSUE TITLE
mismatch shape in stage2

### ISSUE THREAD

**Issue by pribadihcr** [Ldhlwh/DFMGAN#20]
Hi,
I got error when in the stage2

RuntimeError: output with shape [1, 512, 1, 1] doesn't match the broadcast shape [3, 512, 1, 1]

**Comment by pribadihcr** [comment]
sorry I was wrong command to prepare the hazelnut_hole_mask.

**Comment by TimZhang001** [comment]
You can check if the packaging of your defect images is accurate
