### ISSUE TITLE
论文结果的复现

### ISSUE THREAD

**Issue by TimZhang001** [Ldhlwh/DFMGAN#21]
您好，
我这边想要复现论文的测试结果，但是使用Repo的代码测试的结果与论文的结果差别很大。您这边方便把你训练好的PreTrained Model上传供测试吗？

**Comment by Ldhlwh** [comment]
您好，

主页上刚刚更新了hazelnut预训练以及hazelnut_hole模型的链接

**Comment by Liuyangping0322** [comment]
您好，
作者上传的hazelnut_hole.pkl和hazelnut_good.pkl就是训练好的preTrained Model吗
