### ISSUE TITLE
a bug when read gray image

### ISSUE THREAD

**Issue by TimZhang001** [Ldhlwh/DFMGAN#22]
in file dataset_tool.py line 73

img = np.array(PIL.Image.open(fname))

need to be convert to 

# Load image and convert to RGB if needed.
img = np.array(PIL.Image.open(fname).convert('RGB'))

**Comment by Ldhlwh** [comment]
Thanks for your suggestion. Currently this repo only supports RGB images. If you want to use it on grayscale images, I don't recommend converting them into RGB format since the samples rendered by the generator may not be exactly in grayscale. You are encouraged to slightly modify the codes and train a DFMGAN which renders one-channel images.

**Comment by boxbox2** [comment]
> Thanks for your suggestion. Currently this repo only supports RGB images. If you want to use it on grayscale images, I don't recommend converting them into RGB format since the samples rendered by the generator may not be exactly in grayscale. You are encouraged to slightly modify the codes and train a DFMGAN which renders one-channel images.

在MVTEC数据集中，如果我想dest grid_glue_mask它会报如下错误,在我改成img = np.array(PIL.Image.open(fname).convert('RGB'))成功解决了这个问题。
```
  File "dataset_tool.py", line 453, in convert_dataset
    img = np.concatenate((img, np.expand_dims(mask, axis = -1)), axis = 2)
  File "<__array_function__ internals>", line 6, in concatenate
numpy.AxisError: axis 2 is out of bounds for array of dimension 2
```
请问您说的```You are encouraged to slightly modify the codes and train a DFMGAN which renders one-channel images.```指的是什么呢？您是有遇到```numpy.AxisError: axis 2 is out of bounds for array of dimension 2```这个问题吗？

**Comment by Ldhlwh** [comment]
> 请问您说的`You are encouraged to slightly modify the codes and train a DFMGAN which renders one-channel images.`指的是什么呢？

@boxbox2 指的是在灰度图片上训单channel的模型效果可能更好（未经验证），因为可以减少参数并且没有RGB不一致的问题，不过用RGB也能训

**Comment by CVKim** [comment]
@TimZhang001 

Hello,

I created .zip files for the zipper, Toothbrush, and transistor classes using the dataset_tool.py code with the images converted to 'RGB', and then proceeded with training. However, I'm encountering the following issues with the images:

The training for both good and defect classes is being done with rotated images.
As the training progresses, the results are deteriorating.
Have you encountered similar problems? If so, do you know of any solutions?


![image](https://github.com/user-attachments/assets/84cb2502-f4b7-4498-9476-b6c15f171d94)

![image](https://github.com/user-attachments/assets/b13d7431-c8fd-4bbd-8bc8-8ac5e0ef1d15)

**Comment by CVKim** [comment]
@Ldhlwh 

Hi,

I created the dataset.zip using the following code:

img = np.array(PIL.Image.open(fname))
However, when I use these images for training with the resume option, it seems that the training is not working properly, as the images do not seem to be processed correctly.

Could you advise on what might need to be modified?

**Comment by CVKim** [comment]
https://github.com/Ldhlwh/DFMGAN/issues/22#issuecomment-1859045320

![image](https://github.com/user-attachments/assets/3dd3b84c-3b57-4f97-a62b-8198baed522d)


I modified the code in dataset_tool.py as follows, but it seems that there is an issue with proper generation during the training of the good and defect pkls.

Could you advise on which part needs further modification?

'''
img = np.array(PIL.Image.open(fname).convert('RGB'))
'''
