### ISSUE TITLE
使用图片label作为生成条件的疑惑

### ISSUE THREAD

**Issue by leixiaoning** [Ldhlwh/DFMGAN#23]
注意到这行代码 c_dim=0 if self.transfer in ['res_block', 'res_block_match_dis', 'res_block_uni_dis']
想问一下，指定缺陷位置训练阶段，为什么不可以使用label同时作为生成条件？
根据您的代码，如果我要使用 --cond，正确方式应该是？

**Comment by boxbox2** [comment]
> > 注意到这行代码 c_dim=0 if self.transfer in ['res_block', 'res_block_match_dis', 'res_block_uni_dis'] 想问一下，指定缺陷位置训练阶段，为什么不可以使用label同时作为生成条件？ 根据您的代码，如果我要使用 --cond，正确方式应该是？
> 
> 看到这边的mapping网络是对z的mapping，c的mapping网络在后面。。。

这个代码可以使用label生成图片吗？我生成的carpet thead效果很差，您有遇到并解决吗？
