### ISSUE TITLE
it doesn't make any pkls/ng.pkl

### ISSUE THREAD

**Issue by minyeo** [Ldhlwh/DFMGAN#25]
1. The readme instructs to use the pkl file generated in the pkls folder, but both the folder and the file cannot be found. Is it okay to use the network-snapshot-000400.pkl file from the runs folder instead?

2. Is it correct to train NG with the OK pkl file generated during the first training, and then generate defects using the pkl file obtained after training NG? However, the generated images during the generation process do not show any markings on the mask file.
![image](https://github.com/Ldhlwh/DFMGAN/assets/58988225/2d3efe80-cff6-4df4-abab-3cfac7fd018b)
![image](https://github.com/Ldhlwh/DFMGAN/assets/58988225/487864c6-b7c2-4ca2-991b-729453fe021f)
![image](https://github.com/Ldhlwh/DFMGAN/assets/58988225/4e346241-a42e-49ac-a64b-e0cf0bcf4b4c)

**Comment by Ldhlwh** [comment]
1. Of course it is.
2. The procedure is correct. If you failed to render satifying images on your own datasets, consider checking the commands, or describing the datasets (better with examples) to see what could possibly be wrong.
