### ISSUE TITLE
SDGAN, Defect-GAN

### ISSUE THREAD

**Issue by CVKim** [Ldhlwh/DFMGAN#26]
Hello,

I have been studying the DFMGAN paper and found it to be immensely beneficial for my research on surface defect recognition. The concepts of SDGAN and Defect-GAN presented in the paper have particularly piqued my interest.

I am curious about how the SDGAN and Defect-GAN models have been implemented. If possible, could you provide links to any official or unofficial code repositories for these models? Access to such resources would be invaluable for understanding and possibly extending your work.

Thank you for your contributions to the field, 

Best regards!

**Comment by Ldhlwh** [comment]
Glad to hear that DFMGAN is helpful to your research. By the time we did the experiments no public implementation of SDGAN or Defect-GAN was found. I'm not sure whether some relative codes have been released since then, and you may have a look online.
