### ISSUE TITLE
RuntimeError: Ninja is required to load C++ extensions    warnings.warn('Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:\n\n' + traceback.format_exc())

### ISSUE THREAD

**Issue by jiawenchong** [Ldhlwh/DFMGAN#28]
![image](https://github.com/Ldhlwh/DFMGAN/assets/137248552/11ba5939-4847-4ffc-a216-abb22d0f43bf)
I had the run time error during running the code of train.py on defect-free images.

I installed the Ninja package inside my python environment, but the issue still persists.

will the version be an issue of causing this? (the pytorch version I used to be 2.2.1 and the cuda version is 11.8.

**Comment by Ldhlwh** [comment]
> will the version be an issue of causing this? (the pytorch version I used to be 2.2.1 and the cuda version is 11.8.

I'm afraid, yes. You should strictly follow the requirement of the environment of stylegan2-ada-pytorch

**Comment by jiawenchong** [comment]
ok, understood. thanks

**Comment by jiawenchong** [comment]
the stylegan2-ada-pytorch is required pytorch==1.7.1 but the comment inside the torch_utils/ops showed that using pytorch==1.9 so which version is more suitable to use for running the code?

![image](https://github.com/Ldhlwh/DFMGAN/assets/137248552/ca9a6ab1-9b50-47eb-bf42-7d0417d99060)

**Comment by Ldhlwh** [comment]
I vote for 1.7.1 because I'm not sure if 1.9 will do
