### ISSUE TITLE
“Discriminator.b16.conv1.weight”出现异常

### ISSUE THREAD

**Issue by 153201121yf** [Ldhlwh/DFMGAN#29]
<img width="827" alt="微信图片_20240403131504" src="https://github.com/Ldhlwh/DFMGAN/assets/150432118/df3e3b48-73c6-4f61-9510-9463d26addaf">
tick训练到50的时候突然报错tensor和other的值不相等，是什么原因呢，该如何解决

**Comment by Ldhlwh** [comment]
我之前没遇到过类似情况，看起来是stylegan部分多卡ddp出的问题，可以尝试重新训练，如果问题持续出现可以尝试用单卡或者到原stylegan的repo找找解决方案
