### ISSUE TITLE
Runtime error when training: Torch grad

### ISSUE THREAD

**Issue by QasimWani** [Ldhlwh/DFMGAN#3]
**Describe the bug**
When I run train.py (stage I), I get the following error: `RuntimeError: derivative for aten::grid_sampler_2d_backward is not implemented`

This happens in [accumulate_gradients](https://github.com/Ldhlwh/DFMGAN/blob/853505857ebdd5359f1dcd6f0be71ece8e65fdfe/training/loss.py#L263). 

Thought it was related to nvidia ([cuda](https://github.com/NVlabs/stylegan2-ada-pytorch/issues/155)) but now suspect internal torch issue.
- Torch version: 2.0.1
- cuda version: cuda_11.8.r11.8
- Ubuntu OS
- Running 1 GPU A10 on LambdaLabs. 
- python version: 3.8.10

Thoughts??? Time-sensitive issue 🙏🏼

**Comment by Ldhlwh** [comment]
Hello @QasimWani ,

Suppose it is due to pytorch (and/or cuda?) version, try setting up an environment following https://github.com/NVlabs/stylegan2-ada-pytorch#requirements
