### ISSUE TITLE
hazelnut_good.pkl和hazelnut_hole.pkl是如何训练生成的

### ISSUE THREAD

**Issue by Liuyangping0322** [Ldhlwh/DFMGAN#34]
尊敬的作者您好！
如果想尝试其他数据集进行生成图像，例如carpet,如何制作carpet_good.pkl，carpet_hole.pkl
如果能告知具体步骤将不胜感激

**Comment by Ldhlwh** [comment]
按readme流程准备数据和训练即可

**Comment by healer-678** [comment]
感谢回复，但是运行出现报错如下，找不到 "runs/carpet_good/path/to/the/latest/model.pkl"
Constructing networks...
Resuming from "runs/carpet_good/path/to/the/latest/model.pkl"
Traceback (most recent call last):
  File "train.py", line 644, in <module>
    main() # pylint: disable=no-value-for-parameter
.....
FileNotFoundError: [Errno 2] No such file or directory: 'runs/carpet_good/path/to/the/latest/model.pkl'

**Comment by healer-678** [comment]
![Uploading 图片1.png…]()

**Comment by Ldhlwh** [comment]
@healer-678 需要指定正确的路径
