### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by boxbox2** [Ldhlwh/DFMGAN#35]
您好，我的cuda环境是11.3，readme里面python及pytorch版本最高只支持到cuda11.1。请问有其他的环境可以使用吗？

**Comment by boxbox2** [comment]
解决了，直接将stylegan2换成stylegan3即可

**Comment by Ldhlwh** [comment]
请注意DFMGAN没有在StyleGAN3上测试过，不保证能正常运行，需要谨慎使用

**Comment by xiaosu124** [comment]
请问我也遇到这种问题，不换的话该如何处理

**Comment by adha9990** [comment]
@boxbox2 
想请问如何将模型迁移到styglegan3上？

**Comment by boxbox2** [comment]
> [@boxbox2](https://github.com/boxbox2) 想问如何将模型迁移到 styglegan3 上？

直接看3的文档就行

**Comment by adha9990** [comment]
@boxbox2 
你好！
我嘗試使用 StyleGAN3 的 conda 環境（這個環境可以正常訓練 StyleGAN3），來執行 DFMGAN 的第一階段訓練時遇到了一個錯誤：
`RuntimeError: derivative for aten::grid_sampler_2d_backward is not implemented`
我查閱了 StyleGAN3 的文檔，也嘗試了幾天，但還是沒能成功訓練。想請教一下你具體是怎麼把 StyleGAN2 遷移到 StyleGAN3 的？希望能幫忙解答一下，非常感謝！
下面是我執行的過程片段:
`python train.py --data ./data/hazelnut_good.zip --outdir runs/hazelnut_good --gpus 2 --kimg 3000`
```
warnings.warn(f'conv2d_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.conv2d().')
/home/wtlee4500/bluestar/DFMGAN/torch_utils/ops/conv2d_gradfix.py:55: UserWarning: conv2d_gradfix not supported on PyTorch 2.4.1+cu121. Falling back to torch.nn.functional.conv2d().
  warnings.warn(f'conv2d_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.conv2d().')
/home/wtlee4500/bluestar/DFMGAN/torch_utils/ops/conv2d_gradfix.py:55: UserWarning: conv2d_gradfix not supported on PyTorch 2.4.1+cu121. Falling back to torch.nn.functional.conv2d().
  warnings.warn(f'conv2d_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.conv2d().')
/home/wtlee4500/bluestar/DFMGAN/torch_utils/ops/conv2d_gradfix.py:55: UserWarning: conv2d_gradfix not supported on PyTorch 2.4.1+cu121. Falling back to torch.nn.functional.conv2d().
  warnings.warn(f'conv2d_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.conv2d().')
/home/wtlee4500/bluestar/DFMGAN/torch_utils/ops/conv2d_gradfix.py:55: UserWarning: conv2d_gradfix not supported on PyTorch 2.4.1+cu121. Falling back to torch.nn.functional.conv2d().
  warnings.warn(f'conv2d_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.conv2d().')
/home/wtlee4500/bluestar/DFMGAN/torch_utils/ops/conv2d_gradfix.py:55: UserWarning: conv2d_gradfix not supported on PyTorch 2.4.1+cu121. Falling back to torch.nn.functional.conv2d().
  warnings.warn(f'conv2d_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.conv2d().')
/home/wtlee4500/bluestar/DFMGAN/torch_utils/ops/conv2d_gradfix.py:55: UserWarning: conv2d_gradfix not supported on PyTorch 2.4.1+cu121. Falling back to torch.nn.functional.conv2d().
  warnings.warn(f'conv2d_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.conv2d().')
W0401 02:35:37.458957 124439438128640 torch/multiprocessing/spawn.py:146] Terminating process 645801 via signal SIGTERM
Traceback (most recent call last):
  File "train.py", line 644, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 639, in main
    torch.multiprocessing.spawn(fn=subprocess_fn, args=(args, temp_dir), nprocs=args.num_gpus)
  File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 282, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 238, in start_processes
    while not context.join():
  File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 189, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 76, in _wrap
    fn(i, *args)
  File "/home/wtlee4500/bluestar/DFMGAN/train.py", line 472, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "/home/wtlee4500/bluestar/DFMGAN/training/training_loop.py", line 423, in training_loop
    loss.accumulate_gradients(phase=phase.name, real_img=real_img, real_c=real_c, gen_z=gen_z, gen_c=gen_c, sync=sync, gain=gain,
  File "/home/wtlee4500/bluestar/DFMGAN/training/loss.py", line 263, in accumulate_gradients
    (real_logits * 0 + loss_Dreal + loss_Dr1).mean().mul(gain).backward()
  File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/torch/_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 289, in backward
    _engine_run_backward(
  File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/torch/autograd/graph.py", line 769, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: derivative for aten::grid_sampler_2d_backward is not implemented
```

**Comment by boxbox2** [comment]
> [@boxbox2](https://github.com/boxbox2) 你好！ 我嘗試使用 StyleGAN3 的 conda 環境（這個環境可以正常訓練 StyleGAN3），來執行 DFMGAN 的第一階段訓練時遇到了一個錯誤： `RuntimeError: derivative for aten::grid_sampler_2d_backward is not implemented` 我查閱了 StyleGAN3 的文檔，也嘗試了幾天，但還是沒能成功訓練。想請教一下你具體是怎麼把 StyleGAN2 遷移到 StyleGAN3 的？希望能幫忙解答一下，非常感謝！ 下面是我執行的過程片段: `python train.py --data ./data/hazelnut_good.zip --outdir runs/hazelnut_good --gpus 2 --kimg 3000`
> 
> ```
> warnings.warn(f'conv2d_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.conv2d().')
> /home/wtlee4500/bluestar/DFMGAN/torch_utils/ops/conv2d_gradfix.py:55: UserWarning: conv2d_gradfix not supported on PyTorch 2.4.1+cu121. Falling back to torch.nn.functional.conv2d().
>   warnings.warn(f'conv2d_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.conv2d().')
> /home/wtlee4500/bluestar/DFMGAN/torch_utils/ops/conv2d_gradfix.py:55: UserWarning: conv2d_gradfix not supported on PyTorch 2.4.1+cu121. Falling back to torch.nn.functional.conv2d().
>   warnings.warn(f'conv2d_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.conv2d().')
> /home/wtlee4500/bluestar/DFMGAN/torch_utils/ops/conv2d_gradfix.py:55: UserWarning: conv2d_gradfix not supported on PyTorch 2.4.1+cu121. Falling back to torch.nn.functional.conv2d().
>   warnings.warn(f'conv2d_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.conv2d().')
> /home/wtlee4500/bluestar/DFMGAN/torch_utils/ops/conv2d_gradfix.py:55: UserWarning: conv2d_gradfix not supported on PyTorch 2.4.1+cu121. Falling back to torch.nn.functional.conv2d().
>   warnings.warn(f'conv2d_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.conv2d().')
> /home/wtlee4500/bluestar/DFMGAN/torch_utils/ops/conv2d_gradfix.py:55: UserWarning: conv2d_gradfix not supported on PyTorch 2.4.1+cu121. Falling back to torch.nn.functional.conv2d().
>   warnings.warn(f'conv2d_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.conv2d().')
> /home/wtlee4500/bluestar/DFMGAN/torch_utils/ops/conv2d_gradfix.py:55: UserWarning: conv2d_gradfix not supported on PyTorch 2.4.1+cu121. Falling back to torch.nn.functional.conv2d().
>   warnings.warn(f'conv2d_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.conv2d().')
> W0401 02:35:37.458957 124439438128640 torch/multiprocessing/spawn.py:146] Terminating process 645801 via signal SIGTERM
> Traceback (most recent call last):
>   File "train.py", line 644, in <module>
>     main() # pylint: disable=no-value-for-parameter
>   File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "train.py", line 639, in main
>     torch.multiprocessing.spawn(fn=subprocess_fn, args=(args, temp_dir), nprocs=args.num_gpus)
>   File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 282, in spawn
>     return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
>   File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 238, in start_processes
>     while not context.join():
>   File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 189, in join
>     raise ProcessRaisedException(msg, error_index, failed_process.pid)
> torch.multiprocessing.spawn.ProcessRaisedException: 
> 
> -- Process 0 terminated with the following error:
> Traceback (most recent call last):
>   File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 76, in _wrap
>     fn(i, *args)
>   File "/home/wtlee4500/bluestar/DFMGAN/train.py", line 472, in subprocess_fn
>     training_loop.training_loop(rank=rank, **args)
>   File "/home/wtlee4500/bluestar/DFMGAN/training/training_loop.py", line 423, in training_loop
>     loss.accumulate_gradients(phase=phase.name, real_img=real_img, real_c=real_c, gen_z=gen_z, gen_c=gen_c, sync=sync, gain=gain,
>   File "/home/wtlee4500/bluestar/DFMGAN/training/loss.py", line 263, in accumulate_gradients
>     (real_logits * 0 + loss_Dreal + loss_Dr1).mean().mul(gain).backward()
>   File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/torch/_tensor.py", line 521, in backward
>     torch.autograd.backward(
>   File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 289, in backward
>     _engine_run_backward(
>   File "/home/wtlee4500/miniconda3/envs/stylegan3/lib/python3.8/site-packages/torch/autograd/graph.py", line 769, in _engine_run_backward
>     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
> RuntimeError: derivative for aten::grid_sampler_2d_backward is not implemented
> ```

hi ,我后面已经没有在做这个相关了。但我搜索了一下相关问题https://github.com/woctezuma/steam-stylegan2-ada-pytorch/issues/4，这个说不定能帮到你。

**Comment by adha9990** [comment]
@boxbox2 
您好
我已經在您提供的相關問題中成功找到了[解決方法](https://github.com/dvschultz/stylegan2-ada-pytorch/issues/45#issuecomment-1671468176)並且成功完成訓練與生成。
再次感謝您的幫助！
