### ISSUE TITLE
预训练时间

### ISSUE THREAD

**Issue by liuaohunter** [Ldhlwh/DFMGAN#40]
请问我用一张A40在无缺陷图像上训练StyleGAN2,大概需要多长时间呢？一直卡在这里正常吗？
![image](https://github.com/user-attachments/assets/8f0231ab-5116-4d10-928a-bf08060a3b10)

**Comment by Ldhlwh** [comment]
图片里卡住的位置在计算指标，参考https://github.com/Ldhlwh/DFMGAN/issues/7

另外我不太清楚A40的速度，训练开始后会隔一定步数打印信息，可以据此估算

**Comment by liuaohunter** [comment]
![image](https://github.com/user-attachments/assets/32dac979-1743-4a7f-9a57-29797a4f23ac)
![image](https://github.com/user-attachments/assets/fb4eaf09-1884-4d92-ae24-1ef9e3fcc557)
这里默认是fid5k_full，还是卡住怎么回事？

**Comment by Ldhlwh** [comment]
这里显示的默认值是第二阶段的，第一阶段默认是fid50k_full

https://github.com/Ldhlwh/DFMGAN/blob/1bba4d4acae04fb56c51e3a969482c32606b6ffd/train.py#L103-L107

**Comment by liuaohunter** [comment]
不清楚改了之后为啥总是卡在计算指标这里，是因为我只用了一张gpu吗？

**Comment by Ldhlwh** [comment]
如果等了十几二十分钟还没有结果也可能因为环境没配好导致用了速度慢的算子

**Comment by liuaohunter** [comment]
这个模型要求的环境真折磨人
