### ISSUE TITLE
Training MVTec Wood datasets & Different inference results

### ISSUE THREAD

**Issue by jmlee99o** [Ldhlwh/DFMGAN#42]
Hi, I am graduate student in korea.
I want to generate various defective industrial data images by utilizing your model,
so before handling our datas, I use MVTec Wood datasets (Defect : Scratch) to confirm and check the model's performances.

But, when I train model and inference with wood datasets, Its result is quite different with your paper's result.
Both Good and Mask images have not good quality than I expected. (Furthermore, It occurs Overfitting after 400 kimg in good images / Generated Defect images are not similar with MVTec dataset's original scratch things)

I want to know how to optimize the parameters ( that you used ) to develop image qualities.

1. **What parameters did you handle?** (It may be a little rude, but I'm most curious about it.)
2. Did you take other Augmentation tech except for ADA of StyleGAN2 - ADA ?

3.  **This is different from the point**, when I generate a defective image in my dataset, in that model, both normal and defect images are generated and combined from Latent vector, but **can I modify the model** by inputting it into the normal image I have without generating the generated image and combining it with the generated defective image? (**just generating defect images from latent vectors, but not for normal images. because, I think generated normal images of my industrial dataset will have poor quaility.**)

Thanks for reading!
I appreciate for your model services.

**Comment by Ldhlwh** [comment]
I'll close this issue for now since it's been inactive for weeks.
