### ISSUE TITLE
Training Issue with Transistor Class

### ISSUE THREAD

**Issue by CVKim** [Ldhlwh/DFMGAN#43]
<img width="675" alt="image" src="https://github.com/user-attachments/assets/cb35ec31-0bd8-4300-a9cb-3a109bcc71b2">

![image](https://github.com/user-attachments/assets/865dd8dc-c2d6-4ca7-992d-845c73ce54f1)

None of the defect classes for the transistor are being generated properly. Although the training images for the "good" class are created successfully, the images for all defect classes of the transistor are getting corrupted during Stage 2: Transfer learning when using the official GitHub command.

**Comment by CVKim** [comment]
I understand that in the paper's performance evaluation, 1,000 images were generated for each defect class type. On GitHub, it seems like the transfer was done by repeating the process 400 times to generate defect class models, after which 1,000 images were generated for each class, and then only the classification task was used for performance evaluation. Is that correct?

I want to evaluate the performance as described in the paper, so could you provide detailed information on the following?

Fine-tuning method: Did you generate the transfer models by repeating the process 400 times, as mentioned on GitHub?
Performance metrics (classification): How was the performance evaluation for classification conducted? Could you explain the exact steps taken?
Your detailed explanation would be greatly appreciated!

**Comment by CVKim** [comment]
I followed the instructions from [this link](https://github.com/Ldhlwh/DFMGAN/issues/22) and converted the images to RGB format to create the dataset.zip file. Do I need to use a different approach during training because of this conversion?

**Comment by CVKim** [comment]
Could the issue be due to the images being rotated 90 degrees?

**Comment by CVKim** [comment]
@Ldhlwh 

"Is there no solution?"

**Comment by Ldhlwh** [comment]
> Could the issue be due to the images being rotated 90 degrees?

See this issue: https://github.com/Ldhlwh/DFMGAN/issues/6

> I followed the instructions from [this link](https://github.com/Ldhlwh/DFMGAN/issues/22) and converted the images to RGB format to create the dataset.zip file. Do I need to use a different approach during training because of this conversion?

You don't really need to modify this line if you are using RGB images. It is for datasets in grayscale only.


> Fine-tuning method: Did you generate the transfer models by repeating the process 400 times, as mentioned on GitHub?

If you mean 400 kimgs by mentioning *repeating the process 400 times*, then yes.


> Performance metrics (classification): How was the performance evaluation for classification conducted? Could you explain the exact steps taken?

I suppose the description in our paper has already provided sufficient details to reproduce the classification experiments.

**Comment by CVKim** [comment]
![image](https://github.com/user-attachments/assets/a3bcddff-40da-4944-9eed-a37d21ab88a2)

Even with rotate90 and rotate disabled, the issue persists.

The image below is the final kimg result of a normal image, and it doesn't seem to have any noticeable issues, so it's difficult to pinpoint the cause.

**Comment by CVKim** [comment]
@Ldhlwh 

Author, if possible, could you provide pkl files for zipper and transistor model defect types?

I would like to conduct some experiments with them, and they would be incredibly useful. Thank you!

**Comment by Ldhlwh** [comment]
> Even with rotate90 and rotate disabled, the issue persists.
> 
> The image below is the final kimg result of a normal image, and it doesn't seem to have any noticeable issues, so it's difficult to pinpoint the cause.

Not quite sure of the reason. I've never seen similar cases before. I think you may consider turning off the whole ADA.


> Author, if possible, could you provide pkl files for zipper and transistor model defect types?

These files are in a server at my institute (if I didn't clean them up), and unfortunately for some personal reasons I won't be able to access it in a couple of months.

**Comment by CVKim** [comment]
So, to clarify, if I run the provided cmd and code from the official GitHub, everything should work correctly, and the rotation during training shouldn't be an issue, right?

I've trained with normal images before, but I will try again. However, even after multiple trials with normal images, the results were consistently clean, so the issue only arises during defect training.

Also, could you please confirm if using img = np.array(PIL.Image.open(fname).convert('RGB')) when creating the .zip file will resolve the issue?

**Comment by Ldhlwh** [comment]
> So, to clarify, if I run the provided cmd and code from the official GitHub, everything should work correctly, and the rotation during training shouldn't be an issue, right?

The default settings work well for hazelnuts, but do not guarantee to perform as well on other categories. You may have to try different hyparameters and/or tune ADA for better results.

> Also, could you please confirm if using img = np.array(PIL.Image.open(fname).convert('RGB')) when creating the .zip file will resolve the issue?

As I said above, changing this line resolves nothing if you are already using RGB images.

**Comment by xxg1413** [comment]
> <img alt="image" width="675" src="https://private-user-images.githubusercontent.com/90014998/356869242-cb35ec31-0bd8-4300-a9cb-3a109bcc71b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjA3NzQsIm5iZiI6MTcyOTE2MDQ3NCwicGF0aCI6Ii85MDAxNDk5OC8zNTY4NjkyNDItY2IzNWVjMzEtMGJkOC00MzAwLWE5Y2ItM2ExMDliY2M3MWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEwMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MDQ1MTg2MWViYzEyNTUxNjk3OTBiMzFkMGY0MWJmNWE3N2NkYjI4YzE3ZGE4YzQ5YzVmM2YzYzMyYjlhMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DUiJ-HwnuUtrsBIu3wNIUPMzxVWTMP6O0-x6amC60Ls">
> ![image](https://private-user-images.githubusercontent.com/90014998/356936171-865dd8dc-c2d6-4ca7-992d-845c73ce54f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjA3NzQsIm5iZiI6MTcyOTE2MDQ3NCwicGF0aCI6Ii85MDAxNDk5OC8zNTY5MzYxNzEtODY1ZGQ4ZGMtYzJkNi00Y2E3LTk5MmQtODQ1YzczY2U1NGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEwMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NTc0NDM1MTViOTg5YzgxNWFlMGU2NjAzYjkxOGE1N2VhMWFhMTQ2YzkwN2UxZTdlOGVkMzA0YzU1Zjk4OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jFsI3NHs-ru-lYEc5amzbKR868Dbx2W4KmclY7PBBaM)
> 
> None of the defect classes for the transistor are being generated properly. Although the training images for the "good" class are created successfully, the images for all defect classes of the transistor are getting corrupted during Stage 2: Transfer learning when using the official GitHub command.晶体管的所有缺陷类别均未正确生成。尽管成功创建了“良好”类的训练图像，但在第 2 阶段：使用官方 GitHub 命令时，迁移学习期间晶体管所有缺陷类的图像都被损坏。

I trained the zipper, and got the same result as you. The single-channel images don't match the program, but converting them to RGB doesn't seem to work.

Have you solved this issue now? Could you update?
