### ISSUE TITLE
训练时间问题

### ISSUE THREAD

**Issue by lzxssz** [Ldhlwh/DFMGAN#46]
首先感谢作者开源！
请问使用单张A100训练一次大约需要多久呢？

**Comment by Ldhlwh** [comment]
我没有在a100上训过，预计不会超过几个小时

**Comment by lzxssz** [comment]
> 我没有在a100上训过，预计不会超过几个小时

非常感谢回复

**Comment by Ldhlwh** [comment]
> 预计不会超过几个小时

指的是第二阶段，第一阶段时间要长一些

**Comment by lzxssz** [comment]
> > 预计不会超过几个小时
> 
> 指的是第二阶段，第一阶段时间要长一些

您好，请问您在第一阶段大约训练了多久呢？因为课题组资源有限，所以需要向导师说明评估，感谢您的回复！

**Comment by Ldhlwh** [comment]
这个我不记得了，可以去stylegan2-ada-pytorch的库找找参考时间，一阶段就是正常的stylegan训练
