### ISSUE TITLE
关于实验问题

### ISSUE THREAD

**Issue by lzxssz** [Ldhlwh/DFMGAN#47]
作者您好！首先感谢开源！
   关于实验有一些问题：
   1.论文中的表1，与finetune的syleGAN2进行了指标对比，请问是finetune的styleGAN2的训练方式是怎么样的？不知道我的理解对不对：如果是对比榛子hole这一缺陷的KID和LPIPS指标，是否要将hole的真实图片作为训练集，在训练好的hazelnut_good.pkl的基础上继续训练3000个kimg？论文中似乎也没有如果理解有误，恳请您指出。
   2.一个模型是否只能训练一种缺陷类别，具体来说就是，我想统计hole、cut、print等类别生成的KID和LPIPS，是否要分别要训练多个模型分别统计？
   恳请您指点！

**Comment by Ldhlwh** [comment]
> 1.论文中的表1，与finetune的syleGAN2进行了指标对比，请问是finetune的styleGAN2的训练方式是怎么样的？不知道我的理解对不对：如果是对比榛子hole这一缺陷的KID和LPIPS指标，是否要将hole的真实图片作为训练集，在训练好的hazelnut_good.pkl的基础上继续训练3000个kimg？论文中似乎也没有如果理解有误，恳请您指出。

对的，具体训练多少kimg我忘了，但应该不用3000这么多



> 2.一个模型是否只能训练一种缺陷类别，具体来说就是，我想统计hole、cut、print等类别生成的KID和LPIPS，是否要分别要训练多个模型分别统计？

我们公开版本的DFMGAN是的，也可以把代码改成几类缺陷同时训一个模型，但效果一般会比单训差一点

**Comment by lzxssz** [comment]
> > 1.论文中的表1，与finetune的syleGAN2进行了指标对比，请问是finetune的styleGAN2的训练方式是怎么样的？不知道我的理解对不对：如果是对比榛子hole这一缺陷的KID和LPIPS指标，是否要将hole的真实图片作为训练集，在训练好的hazelnut_good.pkl的基础上继续训练3000个kimg？论文中似乎也没有如果理解有误，恳请您指出。
> 
> 对的，具体训练多少kimg我忘了，但应该不用3000这么多
> 
> > 2.一个模型是否只能训练一种缺陷类别，具体来说就是，我想统计hole、cut、print等类别生成的KID和LPIPS，是否要分别要训练多个模型分别统计？
> 
> 我们公开版本的DFMGAN是的，也可以把代码改成几类缺陷同时训一个模型，但效果一般会比单训差一点

感谢回复，如果想改成多个类别训练一个模型，需要怎么改动呢，能否指点一下，感谢！

**Comment by Ldhlwh** [comment]
可以参考一下stylegan2-ada-pytorch多类conditional训练的方式
