### ISSUE TITLE
绿色伪影

### ISSUE THREAD

**Issue by lzxssz** [Ldhlwh/DFMGAN#48]
您好，生成结果含有很多伪影，如图所示
![Snipaste_2024-09-20_14-56-00](https://github.com/user-attachments/assets/1c407780-87e2-4476-96b6-31df44856d24)
请问有什么思路可以抑制这种现象吗

**Comment by Ldhlwh** [comment]
这种情况我前面也遇到过，感觉是训练过程不太稳定导致某些channel整体偏移，换一个checkpoint或者多训几次即可，不会总是出现
