### ISSUE TITLE
can you explain about DFMGAN args briefly?

### ISSUE THREAD

**Issue by MinGiSa** [Ldhlwh/DFMGAN#5]
Hello. Thank you for sharing such a great piece of work.
I'm curious about the following training options # DFMGAN args:
ft = None,
transfer = None,
res_st = None,
uni_st = None,
mask_threshold = None,
lambda_match = None,
mode_seek = None,
lambda_ms = None,
no_round = None,
tanh_k = None,
tanh_mask = None,
dmatch_scale = None
Could you explain them briefly?
And would you recommend changing these options for better results?

**Comment by Ldhlwh** [comment]
Hello @MinGiSa,

Explanations for these args are at Line 528 of ```train.py```. Most of these args are used to set up variations of DFMGAN. You may find details in the ablation study section of the paper.

Generally the default settings of DFMGAN render good performance. I'm not positive that changing these options will give a significant boost.

**Comment by MinGiSa** [comment]
> 

thank you. I'll look for it more.
