### ISSUE TITLE
 MVTec Zipper Problem

### ISSUE THREAD

**Issue by xxg1413** [Ldhlwh/DFMGAN#51]
![fakes_init](https://github.com/user-attachments/assets/b9e7250b-f7f6-40d3-8a3c-09eef183b5c1)

I'm training the zipper dataset, and in the third step, the init images are inconsistent. Could this be the  https://github.com/Ldhlwh/DFMGAN/issues/22 cause? Does changing single-channel images to RGB affect training and inference? 

Below are the images generated from inference.

![24_img](https://github.com/user-attachments/assets/f4bccbbb-6ceb-4c47-82d5-3158cc07898a)

Do you have any other suggestions?

**Comment by Ldhlwh** [comment]
> in the third step, the init images are inconsistent

About *the third step*, do you mean stage 2? Did you run stage 2 when generating these images?

> Could this be the #22  cause?

No. I think the images of MVTec AD are already in RGB format.

**Comment by XXXgejutaixiao** [comment]
Hello, I would like to ask if you set or modified some parameters in the source code during training.
