### ISSUE TITLE
我用自己的图训练后生成的图像错误

### ISSUE THREAD

**Issue by tanshuai555** [Ldhlwh/DFMGAN#52]
原图
![xijian_good](https://github.com/user-attachments/assets/396d0b8d-ff8f-4a90-85e2-2ef9e02398f5)
生成图
![xijian_gen](https://github.com/user-attachments/assets/019db332-43db-45be-bd97-fb21cf051d36)
请问这是怎么回事呢

**Comment by Ldhlwh** [comment]
从例子很难确定原因，用自己的数据训可能需要多调一调才能有好效果
