### ISSUE TITLE
question about few-shot setting

### ISSUE THREAD

**Issue by DaiZhewei** [Ldhlwh/DFMGAN#54]
Hi author,
The introduction to the use of dataset_tool.py provided in the readme documentation doesn't seem to have few-shot setting, 
how should I prepare the dataset according to the setting given in the paper of using only the first 1/3 of the anomalous samples as training data.
Thanks!

**Comment by Ldhlwh** [comment]
You may manually partition the dataset into separate folders before running dataset_tool.py
