### ISSUE TITLE
显存不够，能否给点建议？

### ISSUE THREAD

**Issue by xuyu666** [Ldhlwh/DFMGAN#7]
您好，
我电脑只有12G显存，请问可以跑stylegan2-ada么，能够给点建议（尝试调整batchsize，但会带来一些bug），谢谢~

**Comment by Ldhlwh** [comment]
@xuyu666 您好，

除了减小batch size还可以尝试减少channel，参考train.py里的args.G_kwargs.synthesis_kwargs.channel_base和channel_max

**Comment by xuyu666** [comment]
谢谢你的回复，我尝试了你说的方法，修改成功了。但是运行的时候一直不动了（此时显存貌似没调用，但默认batch16时直接显存不足），具体如下：
![image](https://github.com/Ldhlwh/DFMGAN/assets/49869475/7795dc23-232c-431e-960e-6f584b989118)

**Comment by Ldhlwh** [comment]
看这张图卡住的位置程序应该在算FID，默认要生成50k张图片，本身时间就比较久（几分钟以上）。这里可以尝试```--metrics fid5k_full```减少生成图片数量到5k张确认一下程序是否在正常运行

如果还是卡住，可以检查一下两个pytorch插件有没有配置成功
```
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
```

**Comment by xuyu666** [comment]
好的谢谢，目前去掉指标测试后运行成功。另外想了解下您代码里的rank参数默认为0，能否对其修改。单卡gpu设置为1时，貌似存在一个冲突，具体如图所示。同时我看您论文中有提到supplementary material，能不能发我一份看看哈哈哈（ps: 邮箱2622960263@qq.com）
![批注 2023-07-26 173154](https://github.com/Ldhlwh/DFMGAN/assets/49869475/3fbeb52d-f05d-4c5b-8cde-01925237f39d)

![image](https://github.com/Ldhlwh/DFMGAN/assets/49869475/9389f6a3-b658-4cd7-a3e7-b0ce9d5fe5e0)

**Comment by Ldhlwh** [comment]
rank这部分是StyleGAN-ADA的代码，我没有尝试过修改

补充材料在arxiv版本里有

**Comment by xuyu666** [comment]
有看到，谢谢hahah~
