### ISSUE TITLE
Optimal Batch Size

### ISSUE THREAD

**Issue by researchhappy** [Ldhlwh/DFMGAN#9]
For the sake of time, I am wondering if the default setting for batch size, which I believe is 16, is the optimal for this model. I am wondering if a batch size of 16 is too large and will potentially have the learning rate set too high.

**Comment by Ldhlwh** [comment]
Hello @researchhappy,

These default settings follow StyleGAN2-ADA. Tuning these settings may render slightly better results but is unlikely to give significant boost we suppose

**Comment by researchhappy** [comment]
I see. If the results of the images are of low resolution, are there ways that you suggest in improving the performance of generating normal (i.e. no defects) images? I am currently working with data that are of 1024x1024 size, and the generated images at ~600 kimg are decent but still unclear in some areas. Once it surpasses ~1000 kimg, it becomes very "weird" as in it does not resemble anything like the original dataset.

**Comment by Ldhlwh** [comment]
Could you further describe the datasets you are using and show some dataset images & generated samples here?

**Comment by researchhappy** [comment]
I cannot reveal the images as they are proprietary to the company that I work for. To elaborate in words, however, imagine that I input the image on the left half (i.e. the low resolution half). The generated image is not entirely low in resolution but a portion of it (e.g. the top right corner of the flower) is low in resolution. Continuing to run it after ~600 kimg entirely changes the image into something weird (e.g. turned vertically, the whole image turns black, etc.). I am wondering what I can do to manipulate that small portion that is of low resolution.

Also, the generated images seem to differ decently in terms of darkness. For instance, let us say that the image on the left, the person's face, the generated image has a darker/lighter hair color. Do you have particular suggestions?

**Comment by Ldhlwh** [comment]
I'm afraid I cannot understand your question through your description. An illustration is suggested

**Comment by researchhappy** [comment]
My apologies, I forgot to add this photo. Would this help?

![capture](https://github.com/Ldhlwh/DFMGAN/assets/140681291/a5d50bdd-5457-42b0-9865-bf20e00078ea)

**Comment by Ldhlwh** [comment]
I'm still confused how your case is related to defect generation, especially what kind of images you expect to generate and in which stage (1 or 2) do you have such issue. If you are running stage 2, I suppose the blur you mentioned might be the generated defect.

**Comment by researchhappy** [comment]
This isn't the defect generation stage yet -- this is why it's a problem. I am generating normal images, but certain parts of the images are blur.

**Comment by Ldhlwh** [comment]
In that case, I think consulting the authors of StyleGAN2-ADA would be the best for a solution since the first stage of DFMGAN is basically a StyleGAN.

**Comment by researchhappy** [comment]
I see, thank you. One last question: can I adjust the code to allow the model to accept non-rectangular images (e.g. an image of an apple with the entire background removed)? If so, where can I do this?

**Comment by Ldhlwh** [comment]
You may mask out the background but StyleGAN only accepts square images
